const {baseConfig} = require('@virmator/spellcheck/configs/cspell.config.base.cjs');

module.exports = {
    ...baseConfig,
    ignorePaths: [
        ...baseConfig.ignorePaths,
        '.docusaurus/',
        '*.svg',
        'build/',
    ],
    words: [
        ...baseConfig.words,
        'advfirewall',
        'clsx',
        'cmfcmf',
        'compmgmt',
        'connectaddress',
        'connectport',
        'deno',
        'dsla',
        'frontends',
        'HKLM',
        'infima',
        'inputrc',
        'jwt',
        'kanban',
        'killall',
        'kyler',
        'libvorbis',
        'libvpx',
        'listenaddress',
        'listenport',
        'localport',
        'msvc',
        'nerfed',
        'nerfing',
        'netsh',
        'portproxy',
        'precmd',
        'prereleases',
        'prismock',
        'pwsh',
        'remoteip',
        'subnamespaces',
        'taskkill',
        'transpiles',
        'webm',
        'webrtc',
    ],
};
