name: tests

on:
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Setup Node.js
              uses: actions/setup-node@v4.0.2
              with:
                  node-version-file: '.nvmrc'
            - name: run test
              run: |
                  npm ci
                  npm run test:all
